### ISSUE TITLE
problem too large error in rowMeans inside saver()

### ISSUE THREAD

**Issue by vertesy** [mohuangx/SAVER#26]
Hello!

I am trying to use SAVER, hoping that imputed data will give rise to better gene correlation analysis. Thus, I am running on the RNA slot of a CCA integrated Seurat object. However it breaks down after ~15min.

Did you encounter this problem ?

```r
> require(SAVER)
> data.imputed = saver(combined.obj@assays$RNA@counts, size.factor=1, ncores = 1, do.fast = TRUE)
26690 genes, 82000 cells
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'rowMeans': Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
```

Thank you & Happy New Year!

**Comment by mohuangx** [comment]
I think the issue is the result of the `sweep` function on such a large dataset. I updated the code to remove that function. Can you try installing from the master branch and trying again?

**Comment by vertesy** [comment]
Thank you Mo, I will give it a try over the WE. + sorry for the delay in answering.

**Comment by vertesy** [comment]
Hi, thanks for the fix. So, I tried it:
- It runs
- it ran for long, so I interrupted, and downsampled the object to 8K cells
- I reran, but after ~5 hrs my computer crashed on it.
- From console messages I could see it progressed.
- I can retry with 1 core, but I am afraid it will take 4*5 20 hours, and may still crash.

**Comment by mohuangx** [comment]
Hmm, it's recommended that SAVER be run on the cluster since it tends to be slow on a single computer. If there are particular genes of interest, you could try using the `pred.genes` option so that you're not denoising the entire dataset. If you still want to denoise the entire dataset, I would recommend looking into other denoising algorithms such as scVI or DCA which are faster. 

Sorry for not being able to help more!
